<?php 

// agenda 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_54f80a1a7d936',
	'title' => 'Agenda',
	'fields' => array (
		array (
			'display_format' => 'd/m/Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
			'key' => 'field_54afc57a46488',
			'label' => 'Start Datum',
			'name' => 'uu_agenda_start_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'display_format' => 'd/m/Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
			'key' => 'field_54afc5c646489',
			'label' => 'Eind datum',
			'name' => 'uu_agenda_end_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_54afc6714648c',
			'label' => 'Geen tijd',
			'name' => 'uu_agenda_all_day',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'display_format' => 'H:i',
			'return_format' => 'H:i',
			'key' => 'field_54afc5d94648a',
			'label' => 'Start tijd',
			'name' => 'uu_agenda_start_time',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54afc6714648c',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'display_format' => 'H:i',
			'return_format' => 'H:i',
			'key' => 'field_54afc6414648b',
			'label' => 'Eind tijd',
			'name' => 'uu_agenda_end_time',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54afc6714648c',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_54afc6bb4648d',
			'label' => 'Locatie',
			'name' => 'uu_agenda_location',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'formatting' => 'html',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_54afc6d94648e',
			'label' => 'Url',
			'name' => 'uu_agenda_url',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'formatting' => 'html',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
			'key' => 'field_54afc6fc4648f',
			'label' => 'Afbeelding',
			'name' => 'uu_agenda_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
			array (
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:agenda',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
			array (
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:agenda-en',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

//people
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_54f80a1a96a0c',
	'title' => 'People',
	'fields' => array (
		array (
			'sub_fields' => array (
				array (
					'layout' => 'horizontal',
					'choices' => array (
						'Kop' => 'Kop',
						'Persoon' => 'Persoon',
					),
					'default_value' => 'Persoon',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
					'key' => 'field_54b8dbc2b1f34',
					'label' => 'Type veld',
					'name' => 'uu_people_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_54b8d08437d2b',
					'label' => 'Naam',
					'name' => 'uu_people_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54b8dbc2b1f34',
								'operator' => '==',
								'value' => 'Persoon',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'formatting' => 'html',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_54b8d08937d2c',
					'label' => 'Titel',
					'name' => 'uu_people_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54b8dbc2b1f34',
								'operator' => '==',
								'value' => 'Persoon',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'formatting' => 'html',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => '',
					'key' => 'field_54b8d09737d2d',
					'label' => 'Omschrijving',
					'name' => 'uu_people_desc',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54b8dbc2b1f34',
								'operator' => '==',
								'value' => 'Persoon',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_54b8d0a037d2e',
					'label' => 'Website',
					'name' => 'uu_people_website',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54b8dbc2b1f34',
								'operator' => '==',
								'value' => 'Persoon',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'formatting' => 'html',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_54b8d0a737d2f',
					'label' => 'Email',
					'name' => 'uu_people_email',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54b8dbc2b1f34',
								'operator' => '==',
								'value' => 'Persoon',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'formatting' => 'html',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => 0,
					'min_height' => 0,
					'min_size' => 0,
					'max_width' => 0,
					'max_height' => 0,
					'max_size' => 0,
					'mime_types' => '',
					'key' => 'field_54b8d0ab37d30',
					'label' => 'Foto',
					'name' => 'uu_people_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_54b8efd13d0c5',
					'label' => 'Titel kop',
					'name' => 'uu_people_title_heading',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54b8dbc2b1f34',
								'operator' => '==',
								'value' => 'Kop',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'formatting' => 'html',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Voeg persoon toe',
			'collapsed' => '',
			'key' => 'field_54b8d06b37d2a',
			'label' => 'Persoon',
			'name' => 'persoon',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-people.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-people-large.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;